version: '3.8'

services:
  server:
    build: .
    command: java -jar udp.jar server
    ports:
      - "1234:1234" # Device port
      - "5678:5678" # Client port

  client:
    build: .
    command: java -jar udp.jar client
    stdin_open: true
    tty: true
    depends_on:
      - server

  device1:
    build: .
    command: java -jar udp.jar device --port 1234 --type "Light"
    stdin_open: true
    tty: true
    depends_on:
      - server

  device2:
    build: .
    command: java -jar udp.jar device --port 1234 --type "Thermostat"
    stdin_open: true
    tty: true
    depends_on:
      - server
