version: '3.8'

services:
  server:
    build: .
    command: java -jar udp.jar server
    ports:
      - "1234:1234" # Device port
      - "5678:5678" # Client port

  client:
    build: .
    command: java -jar udp.jar client

  device:
    build: .
    command: java -jar udp.jar device --port 1234 --type "${DEVICE_TYPE}"
    environment:
      DEVICE_TYPE: default # Default device type
